[package]
name = "md5-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
md5 = "0.7.0"
rand = "0.8.4"
rustc-serialize = "0.3.24"
